"""model_review_v2

Revision ID: 5a7e9db4919c
Revises: 8f8fc05b0864
Create Date: 2026-05-29 08:29:36.955258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a7e9db4919c'
down_revision: Union[str, Sequence[str], None] = '8f8fc05b0864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_fiscais', sa.Column('fonte', sa.String(length=3), nullable=True))
    op.alter_column('documentos_fiscais', 'vl_doc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_desc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_merc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_bc_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_bc_icms_st',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_icms_st',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_pis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_cofins',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.create_unique_constraint('uq_documento_tenant_chave', 'documentos_fiscais', ['tenant_id', 'chv_nfe'])
    op.alter_column('fabricantes', 'aliases',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='aliases::jsonb')
    op.alter_column('icms_c190', 'aliq_icms',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True,
               postgresql_using='aliq_icms::numeric')
    op.alter_column('icms_c190', 'vl_opr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_bc_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_bc_icms_st',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_icms_st',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_red_bc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_pis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_cofins',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.add_column('itens_fiscais', sa.Column('cst_pis', sa.String(length=3), nullable=True))
    op.add_column('itens_fiscais', sa.Column('cst_cofins', sa.String(length=3), nullable=True))
    op.add_column('itens_fiscais', sa.Column('aliq_pis', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('itens_fiscais', sa.Column('aliq_cofins', sa.Numeric(precision=7, scale=4), nullable=True))
    op.alter_column('itens_fiscais', 'qtd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_item',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_desc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_bc_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'aliq_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_icms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_pis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_cofins',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    # Renomear chv_doc → chv_nfe para padronizar o nome da chave NF-e em todas as tabelas
    op.alter_column('itens_fiscais', 'chv_doc', new_column_name='chv_nfe')
    op.alter_column('icms_c190', 'chv_doc', new_column_name='chv_nfe')
    op.create_unique_constraint('uq_item_tenant_chave', 'itens_fiscais', ['tenant_id', 'chv_nfe', 'num_item'])
    op.alter_column('marcas', 'aliases',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='aliases::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marcas', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_item_tenant_chave', 'itens_fiscais', type_='unique')
    op.alter_column('itens_fiscais', 'chv_nfe', new_column_name='chv_doc')
    op.alter_column('icms_c190', 'chv_nfe', new_column_name='chv_doc')
    op.alter_column('itens_fiscais', 'vl_cofins',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_pis',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_icms',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'aliq_icms',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_bc_icms',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_desc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'vl_item',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('itens_fiscais', 'qtd',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('itens_fiscais', 'aliq_cofins')
    op.drop_column('itens_fiscais', 'aliq_pis')
    op.drop_column('itens_fiscais', 'cst_cofins')
    op.drop_column('itens_fiscais', 'cst_pis')
    op.alter_column('icms_c190', 'vl_cofins',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_pis',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_red_bc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_icms_st',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_bc_icms_st',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_icms',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_bc_icms',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'vl_opr',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('icms_c190', 'aliq_icms',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('fabricantes', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_documento_tenant_chave', 'documentos_fiscais', type_='unique')
    op.alter_column('documentos_fiscais', 'vl_cofins',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_pis',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_icms_st',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_bc_icms_st',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_icms',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_bc_icms',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_merc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_desc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('documentos_fiscais', 'vl_doc',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('documentos_fiscais', 'fonte')
    # ### end Alembic commands ###
