"""add_gold_kpis_mensais

Revision ID: a04f951ab3d1
Revises: c7d8e9f0a1b2
Create Date: 2026-06-22 14:39:09.903126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04f951ab3d1'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_kpis_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('vl_faturamento', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qtd_notas_saida', sa.Integer(), nullable=True),
    sa.Column('ticket_medio', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_compras', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qtd_notas_entrada', sa.Integer(), nullable=True),
    sa.Column('vl_icms_debito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms_credito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms_pagar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_pis', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_cofins', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ano', 'mes', name='uq_gold_kpis_tenant_ano_mes')
    )
    op.create_index(op.f('ix_gold_kpis_mensais_tenant_id'), 'gold_kpis_mensais', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_participantes_id'), table_name='fornecedores')
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.drop_index(op.f('ix_itens_fiscais_id'), table_name='itens_nota_fiscal')
    op.create_index(op.f('ix_itens_nota_fiscal_id'), 'itens_nota_fiscal', ['id'], unique=False)
    op.drop_index(op.f('ix_tenants_id'), table_name='lojas')
    op.create_index(op.f('ix_lojas_id'), 'lojas', ['id'], unique=False)
    op.drop_index(op.f('ix_documentos_fiscais_id'), table_name='notas_fiscais')
    op.create_index(op.f('ix_notas_fiscais_id'), 'notas_fiscais', ['id'], unique=False)
    op.drop_index(op.f('ix_icms_c190_id'), table_name='resumo_fiscal')
    op.create_index(op.f('ix_resumo_fiscal_id'), 'resumo_fiscal', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumo_fiscal_id'), table_name='resumo_fiscal')
    op.create_index(op.f('ix_icms_c190_id'), 'resumo_fiscal', ['id'], unique=False)
    op.drop_index(op.f('ix_notas_fiscais_id'), table_name='notas_fiscais')
    op.create_index(op.f('ix_documentos_fiscais_id'), 'notas_fiscais', ['id'], unique=False)
    op.drop_index(op.f('ix_lojas_id'), table_name='lojas')
    op.create_index(op.f('ix_tenants_id'), 'lojas', ['id'], unique=False)
    op.drop_index(op.f('ix_itens_nota_fiscal_id'), table_name='itens_nota_fiscal')
    op.create_index(op.f('ix_itens_fiscais_id'), 'itens_nota_fiscal', ['id'], unique=False)
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.create_index(op.f('ix_participantes_id'), 'fornecedores', ['id'], unique=False)
    op.drop_index(op.f('ix_gold_kpis_mensais_tenant_id'), table_name='gold_kpis_mensais')
    op.drop_table('gold_kpis_mensais')
    # ### end Alembic commands ###
